---
- hosts: all
  become: true
  tasks: 
  - name: Download epel.repo
    get_url:
     url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
     dest: /root/epel-release-latest-6.noarch.rpm
     mode: 0440
  - name: Download Zabbix Repo
    get_url:
     url: http://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm
     dest: /root/zabbix-release-4.0-1.el6.noarch.rpm
     mode: 0440
  - name: install epel rpm from a local file
    yum:
     name: /root/epel-release-latest-6.noarch.rpm
     state: present
  - name: install Zabbix rpm from a local file
    yum:
     name: /root/zabbix-release-4.0-1.el6.noarch.rpm
     state: present
  - name: install php repo
    yum:
     name: https://mirror.webtatic.com/yum/el6/latest.rpm
     state: present
  - name: Install software
    yum:  
     name: 
     - httpd
     - php
     - php-mcrypt 
     - php-cli 
     - php-gd 
     - php-curl 
     - php-mysql 
     - php-ldap 
     - php-zip 
     - php-fileinfo
     - MariaDB-client
     - MariaDB-server
     state: present
  - name: copy mariadb repo
    copy: 
     src: MariaDB.repo
     dest: /etc/yum.repos.d/MariaDB.repo
  - name: start httpd service
    service: 
     name: httpd
     state: started
     enabled: yes 
  - name: start mariadb service     
    service:      
     name: mysql      
     state: started      
     enabled: yes
  - name: install zabbix
    yum: 
     name:
     - zabbix-get 
     - zabbix-server-mysql 
     - zabbix-web-mysql 
     - zabbix-agent
     state: present
