---
- hosts: all
  become: true
  tasks: 
  - name: Download epel.repo
    get_url:
     url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
     dest: /root/epel-release-latest-6.noarch.rpm
     mode: 0440
  - name: Download Zabbix Repo
    get_url:
     url: http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-web-4.0.0-2.el7.noarch.rpm
     dest: /root/zabbix-web-4.0.0-2.el7.noarch.rpm
     mode: 0440
  - name: install epel rpm from a local file
    yum:
     name: /ec2-user/epel-release-latest-7.noarch.rpm
     state: present
  - name: install Zabbix rpm from a local file
    yum:
     name: /root/zabbix-web-4.0.0-2.el7.noarch.rpm
     state: present
  - name: install zabbix-agent
    yum: 
     name: zabbix-agent 
     state: latest
  - name: copy zabbix configuration file
    copy: src=/etc/zabbix/zabbix_agentd.conf dest=/etc/zabbix_agentd.conf
  - name: restart Zabbix Service
    service: name=zabbix-agent state=started enabled=yes
